### ISSUE TITLE
[TIMEBOX] Figure out how we are building the UI

### ISSUE THREAD

**Issue by gxldCptRick** [Carrera-Dev-Consulting/zombie-nomnom-ui#14]
Find a framework to build the UI from currently it is using Next.js but look around and see if there are other things we can use to refresh and boostrap the app.

**Comment by Furman950** [comment]
Express.js ?

**Comment by vCertxfiedGoat** [comment]
We are using nextjs

**Comment by gxldCptRick** [comment]
Boo
